apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-service.name" . }}
  labels: {{- include "model-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "model-service.selector" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
